# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-18.04.1.box"
 	config.vm.hostname = "ubuntu-18.04.1.box"
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

   
config.vm.provider "virtualbox" do |vb|
  vb.name = "ubuntu-1804"
  vb.memory = "1024"
  vb.cpus = 1
  end
    
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["site-cookbooks", "cookbooks"]
    chef.roles_path = "roles"
    chef.data_bags_path = "data_bags"
    chef.provisioning_path = "/tmp/vagrant-chef"

    chef.run_list = VAGRANT_JSON.delete('run_list')
    chef.json = VAGRANT_JSON
    end
end
