apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-flask
  labels:
    app: nginx-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-flask
  template:
    metadata:
      labels:
        app: nginx-flask
    spec:
      containers:
      - name: nginx-flask
        image: johnnybravo6/firs-test:0
        ports:
        - containerPort: 5000



