Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  #config.disksize.size = '13GB'
  config.vm.box_check_update = false
  config.vm.define "web-server" do |subconfig|
    # имя виртуальной машины
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "web-server"
      vb.memory = "2608"
      vb.cpus = 2
    end
    subconfig.vm.hostname = "web-server"
    subconfig.vm.network "private_network", ip: "192.168.10.10"
    #subconfig.vm.provision "shell", path: "create_dev_env.sh"
    config.ssh.insert_key = false
    config.ssh.private_key_path = ["./vagrant_rsa", "~/.vagrant.d/insecure_private_key"]
    config.vm.provision "file", source: "./vagrant_rsa.pub", destination: "~/.ssh/authorized_keys"

  end
end
