apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-01
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: "/mnt/data/prometheus01"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-alert
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1024Mi
  hostPath:
    path: "/mnt/data/prometheus02"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-01
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data/grafana01"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv01
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data/wordpress01"
